### ISSUE TITLE
Error "Invalid command: AccessControl::IsUserTheAdministrator"

### ISSUE THREAD

**Issue by himei** [clear-code/fx-meta-installer#2]
I use fx-meta-installer on Windows XP, and I installed AccessControll.dll and other required plugins into NSIS plugin folder.
then, I got following error messages:

...
File: "AccessControl.dll"->"$PLUGINSDIR\AccessControl.dll" [compress] 6008/8192 bytes
Plugin Command: GetCurrentUserName
Pop: $0
Invalid command: AccessControl::IsUserTheAdministrator
Error in script "fainstall.nsi" on line 1812 -- aborting creation process
"Failed to build fainstall.exe!"

**Comment by kenhys** [comment]
Close this issue because #5 was merged.
