### ISSUE TITLE
Remove installed xpi correctly

### ISSUE THREAD

**Issue by myokoym** [clear-code/fx-meta-installer#9]

**Comment by myokoym** [comment]
Maybe we should also remove installed `C:\Program Files (x86)\ClearCode Inc\XXXInstaller`.

**Comment by piroor** [comment]
5dee1f8d54ee61cb997c3fb5f91029b9053207fb should fix this.

**Comment by piroor** [comment]
Finally fixed by 5726991b4764201ab6584245b41f439f0e9ecc6d.
